---
# This configuration defaults to the `development` environment

# Doctrine configuration
DOCTRINE_DEV_MODE: 1

# Twig configuration
TWIG_DEBUG: 1

# RabbitMQ configuration
RABBIT_MQ_USER: "guest"
RABBIT_MQ_PASSWORD: "guest"
RABBIT_MQ_HOST: "queue"

# MySQL configuration
MYSQL_ROOT_PASSWORD: "root"

# MySQL application configuration
MYSQL_USER: "ewallet_user"
MYSQL_PASSWORD: "ewallet_password"
MYSQL_HOST: "db"
