engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
  - "**/vendor"
  - "applications/console/config.php"
  - "applications/dev/config.php"
  - "applications/messaging/config.php"
  - "applications/web/config.php"
  - "applications/console/config.tests.php"
  - "applications/messaging/config.tests.php"
  - "applications/web/config.tests.php"
  - "applications/web/tests/_support/_generated"
