language: php

dist: trusty

php:
  - 7.4

services:
  - rabbitmq

addons:
  chrome: stable

before_script:
  - sudo apt-get install libzip-dev
  - pecl install zip
  - composer self-update
  - cd ui/console && composer install --prefer-source --no-interaction
  - cd ../messaging && composer install --prefer-source --no-interaction
  - cp .env.travis .env.tests
  - cd ../web && composer install --prefer-source --no-interaction
  - wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
  - sudo chmod +x /usr/local/bin/chromedriver
  - cd ../../ewallet && composer install --prefer-source --no-interaction
  - cp .env.travis .env.tests
  - cd ..

script:
  - make check
