language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - npm install
  - bin/doctrine orm:schema-tool:create

script:
  - bin/phpspec run -v
  - bin/behat -v
  - bin/phpunit
  - bin/robo acceptance
