language: php

php:
  - 7.1

services:
  - rabbitmq

before_script:
  - composer self-update
  - cd ui/console && composer install --prefer-source --no-interaction
  - cd ../messaging && composer install --prefer-source --no-interaction
  - cp .env.travis .env.tests
  - cd ../web && composer install --prefer-source --no-interaction
  - npm install -g phantomjs-prebuilt
  - cd ../../ewallet && composer install --prefer-source --no-interaction
  - cp .env.travis .env.tests

script:
  - cd ../ui/console && vendor/bin/phpunit -v
  - cd ../messaging && vendor/bin/phpunit -v
  - cd ../web && bin/phpunit -v
  - bin/robo acceptance
  - cd ../../ewallet && vendor/bin/phpspec run -v
  - vendor/bin/behat -v
  - vendor/bin/phpunit -v
