language: php

php:
  - 7.2

services:
  - rabbitmq

before_script:
  - composer self-update
  - cd ui/console && composer install --prefer-source --no-interaction
  - cd ../messaging && composer install --prefer-source --no-interaction
  - cp .env.travis .env.tests
  - cd ../web && composer install --prefer-source --no-interaction
  - npm install -g phantomjs-prebuilt
  - cd ../../ewallet && composer install --prefer-source --no-interaction
  - cp .env.travis .env.tests

script:
  - make check
