language: php

php:
  - 7.0

services:
  - rabbitmq
  - mysql

before_script:
  - composer self-update
  - cd applications/console && composer install --prefer-source --no-interaction --dev
  - mysql -e 'create database ewallet_db;'
  - cp .env.travis .env && cp ../../containers/templates/cli-config.php cli-config.php && ENV=testing bin/doctrine orm:schema-tool:create
  - cd ../messaging && composer install --prefer-source --no-interaction --dev
  - cp .env.travis .env
  - cd ../web && composer install --prefer-source --no-interaction --dev
  - cp .env.travis .env && cp ../../containers/templates/cli-config.php cli-config.php  && bin/doctrine orm:schema-tool:create
  - npm install -g phantomjs-prebuilt
  - cd ../../packages/ewallet/domain && composer install --prefer-source --no-interaction --dev
  - cd ../application && composer install --prefer-source --no-interaction --dev
  - cd ../doctrine && composer install --prefer-source --no-interaction --dev
  - cp ../../../containers/templates/cli-config.php cli-config.php && bin/doctrine orm:schema-tool:create
  - cd ../responder && composer install --prefer-source --no-interaction --dev
  - cp ../../../containers/templates/cli-config.php cli-config.php && bin/doctrine orm:schema-tool:create
  - cd ../templating && composer install --prefer-source --no-interaction --dev
  - cd ../validation && composer install --prefer-source --no-interaction --dev
  - cd ../../hexagonal/doctrine && composer install --prefer-source --no-interaction --dev
  - cp ../../../containers/templates/cli-config.php cli-config.php && bin/doctrine orm:schema-tool:create

script:
  - cd ../../../applications/console && bin/phpunit -v
  - cd ../messaging && bin/phpunit -v
  - cd ../web && bin/phpunit -v
  - bin/robo acceptance
  - cd ../../packages/ewallet/domain && bin/phpspec run -v
  - bin/behat -v
  - cd ../application && bin/phpunit -v
  - cd ../doctrine && bin/phpunit -v
  - cd ../responder && bin/phpunit -v
  - cd ../templating && bin/phpunit -v
  - cd ../validation && bin/phpunit -v
  - cd ../../hexagonal/doctrine && bin/phpunit -v
