language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

services:
  - rabbitmq
  - mysql

before_script:
  - composer self-update
  - cd applications/console && composer install --prefer-source --no-interaction --dev
  - mysql -e 'create database ewallet_db;'
  - cp .env.travis .env && bin/doctrine orm:schema-tool:create
  - cd ../messaging && composer install --prefer-source --no-interaction --dev
  - cd ../web && composer install --prefer-source --no-interaction --dev
  - npm install -g phantomjs
  - cd ../../packages/ewallet/domain && composer install --prefer-source --no-interaction --dev

script:
  - cd applications/console && bin/phpunit -v
  - cd applications/messaging && bin/phpunit -v
  - cd applications/web && bin/phpunit -v
  - cd applications/web bin/robo acceptance
  - cd packages/ewallet/domain && bin/phpspec run -v
  - cd packages/ewallet/domain && bin/behat -v
