language: php

php:
  - 7.1

services:
  - rabbitmq

before_script:
  - composer self-update
  - cd ui/console && composer install --prefer-source --no-interaction --dev
  - cd ../messaging && composer install --prefer-source --no-interaction --dev
  - cp .env.travis .env.tests
  - cd ../web && composer install --prefer-source --no-interaction --dev
  - cp ../../containers/templates/index_dev.php public/index_dev.php
  - npm install -g phantomjs-prebuilt
  - cd ../../ewallet && composer install --prefer-source --no-interaction --dev
  - cp ../../../containers/templates/cli-config.php cli-config.php
  - cd ../messaging && composer install --prefer-source --no-interaction --dev
  - cp .env.travis .env.tests

script:
  - cd ../../../ui/console && bin/phpunit -v
  - cd ../messaging && bin/phpunit -v
  - cd ../web && bin/phpunit -v
  - bin/robo acceptance
  - cd ../../ewallet && bin/phpspec run -v
  - bin/behat -v
  - bin/phpunit -v
  - cd ../messaging && bin/phpunit -v
