---
- hosts: localhost

  vars_files:
    - vars/dev.yml

  tasks:
    - name: Copy Apache vhost configuration template.
      template: src={{ ansible_env.PWD }}/web/templates/ewallet.conf.j2 dest={{ ansible_env.PWD }}/web/templates/ewallet.conf

    - name: Copy .env file for console application
      template: src={{ ansible_env.PWD }}/setup/templates/.env.j2 dest={{ ansible_env.PWD }}/../.env

    - name: Copy auth.json to ease composer installation
      template: src={{ ansible_env.PWD }}/setup/templates/auth.json.j2 dest={{ ansible_env.PWD }}/setup/config/auth.json

    - name: Build data container.
      command: docker build -t ewallet:data data

    - name: Pull MySQL container.
      command: docker pull mysql:5.6.27

    - name: Pull RabbitMQ container.
      command: docker pull rabbitmq:3.5

    - name: Pull Ruby container.
      command: docker pull ruby:2.3

    - name: Build MailCatcher container.
      command: docker build -t ewallet:mail mail

    - name: Build messaging container.
      command: docker build -t ewallet:messaging messaging

    - name: Build Web application container.
      command: docker build -t ewallet:web web

    - name: Build console application container.
      command: docker build -t ewallet:console console

    - name: Build container to setup the application.
      command: docker build -t ewallet:setup setup

    - name: Build tests container.
      command: docker build -t ewallet:tests tests
