---
- hosts: localhost

  vars_files:
    - vars/dev.yml

  tasks:
    - name: Make sure ewallet data container is present.
      docker:
        image: ewallet:data
        name: data
        state: present

    - name: Run ewallet MySQL container.
      docker:
        image: mysql:5.6.27
        name: db
        state: running
        volumes_from: data
        ports: "3308:3306"
        env:
            MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
            MYSQL_USER: "{{ MYSQL_USER }}"
            MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
            MYSQL_DATABASE: "ewallet_db"

    - name: Run ewallet RabbitMQ container.
      docker:
        image: rabbitmq:3.5
        name: queue
        state: running
        ports: "5674:5672"
        env:
            RABBITMQ_DEFAULT_USER: "{{ RABBIT_MQ_USER }}"
            RABBITMQ_DEFAULT_PASS: "{{ RABBIT_MQ_PASSWORD }}"

    - name: Run ewallet MailCatcher container.
      docker:
        image: ewallet:mail
        name: mail
        state: running
        ports: "8080:8080"

    - name: Run messaging container.
      docker:
        image: ewallet:messaging
        name: messaging
        state: running
        ports: "8080:8080"
