imports:
  - { resource: doctrine.yml }
  - { resource: validation.yml }
  - { resource: ewallet.yml }
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Symfony\Component\Console\Input\InputInterface:
    public: true
    class: Symfony\Component\Console\Input\ArgvInput
  Symfony\Component\Console\Output\OutputInterface:
    public: true
    class: Symfony\Component\Console\Output\ConsoleOutput
  Ewallet\Ui\Console\Commands\TransferFundsConsole:
  Ewallet\UI\Console\Commands\:
    public: true
    resource: '../src/UI/Console/Commands/*'
