---
- name: Make sure ewallet data container is running.
  docker:
    image: ewallet:data
    name: data
    state: present

- name: Run ewallet MySQL container.
  docker:
    image: mysql:5.6.27
    name: db
    state: running
    volumes_from: data
    ports: "3308:3306"
    env:
        MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
        MYSQL_USER: "{{ MYSQL_USER }}"
        MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
        MYSQL_DATABASE: "ewallet_db"

- name: Run ewallet RabbitMQ container.
  docker:
    image: rabbitmq:3.5
    name: messaging
    state: running
    ports: "5674:5672"
    env:
        RABBITMQ_DEFAULT_USER: "{{ RABBIT_MQ_USER }}"
        RABBITMQ_DEFAULT_PASS: "{{ RABBIT_MQ_PASSWORD }}"

- name: Run PHP CLI container.
  command: docker run -t --rm \
            --name setup \
            -v "{{ ansible_env.PWD }}/../:/usr/src/myapp" \
            -w /usr/src/myapp \
            --link db:db \
            --link messaging:messaging \
            ewallet:setup \
            make install
