---
- name: Run PHP CLI container.
  command: docker run -t --rm \
            --name setup \
            -v "{{ ansible_env.PWD }}/../:/usr/src/myapp" \
            -w /usr/src/myapp \
            --link db:db \
            --link messaging:messaging \
            ewallet:setup \
            make install
