---
- name: Make sure ewallet data container is running.
  docker:
    image: ewallet:data
    name: data
    state: present

- name: Run ewallet MySQL container.
  docker:
    image: mysql:5.6.27
    name: db
    state: running
    volumes_from: data
    ports: "3308:3306"
    env:
        MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
        MYSQL_USER: "{{ MYSQL_USER }}"
        MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
        MYSQL_DATABASE: "ewallet_db"

- name: Run all the tests.
  command: docker run -t --rm \
            --name tests \
            -v "{{ ansible_env.PWD }}/../:/usr/src/myapp" \
            -w /usr/src/myapp \
            --link db:db \
            ewallet:tests \
            php bin/robo test
  register: test_results

- debug: msg="{{ test_results.stdout }}"
