<?php
/**
 * PHP version 7.1
 *
 * This source file is subject to the license that is bundled with this package in the file LICENSE.
 */
namespace Ewallet\Slim\Middleware;

use Application\DomainEvents\EventPublisher;
use Application\DomainEvents\PersistEventsSubscriber;

class StoreEventsMiddleware
{
    /** @var PersistEventsSubscriber */
    private $subscriber;

    /** @var EventPublisher */
    private $publisher;

    public function __construct(PersistEventsSubscriber $subscriber, EventPublisher $publisher)
    {
        $this->subscriber = $subscriber;
        $this->publisher = $publisher;
    }

    /**
     * Register event subscriber to persist all domain events generated by
     * the web application
     */
    public function __invoke($request, $response, $next)
    {
        $this->publisher->subscribe($this->subscriber);

        return $next($request, $response);
    }
}
