<?php
/**
 * PHP version 5.6
 *
 * This source file is subject to the license that is bundled with this package in the file LICENSE.
 */
namespace Ewallet\Slim\Middleware;

use Hexagonal\DomainEvents\EventPublisher;
use Hexagonal\DomainEvents\PersistEventsSubscriber;
use Slim\Middleware;

class StoreEventsMiddleware extends Middleware
{
    /** @var PersistEventsSubscriber */
    private $subscriber;

    /** @var EventPublisher */
    private $publisher;

    /**
     * @param PersistEventsSubscriber $subscriber
     * @param EventPublisher $publisher
     */
    public function __construct(
        PersistEventsSubscriber $subscriber,
        EventPublisher $publisher
    ) {
        $this->subscriber = $subscriber;
        $this->publisher = $publisher;
    }

    /**
     * Register event subscriber to persist all domain events generated by
     * the web application
     */
    public function call()
    {
        $this->publisher->subscribe($this->subscriber);

        $this->next->call();
    }
}
